name: Automerge

on: push

env:
  MY_REPO: https://Darxoon:${{secrets.GITHUB_TOKEN}}@github.com/Darxoon/OrigamiWand.git

  MY_BRANCH: build

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/Darxoon/OrigamiWand.git

  MASTER_BRANCH: master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push