name: Build OrigamiWand Releases

on:
  push:
    paths:
      - '.github/workflows/*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install npm dependencies
      run: npm install
      
    - name: Get latest git tag
      id: get_latest_tag
      run: echo "TAG_NAME=$(git for-each-ref --count=1 --sort=-taggerdate --format '%(tag)' refs/tags)" >> $GITHUB_OUTPUT
      
    - name: Build OrigamiWand
      run: PUBLIC_OW_VERSION="${{ steps.get_latest_tag.outputs.TAG_NAME }}" PUBLIC_VERSION_TIMESTAMP=$(date +%s)000 PUBLIC_IS_DEV_VERSION=0 PUBLIC_DEBUG=0 npm run build
    
    # - name: Create zip of build folder
    #   run: cd build && zip -r ../out.zip .
      
    - name: Upload build folder
      uses: actions/upload-artifact@v3.1.3
      with:
        name: OrigamiWand-build
        path: build
        
